<!DOCTYPE html>


<!-- LUis rodriguez - 0812903 -->

<html>
<head>
    <title>Insert Inventory</title>
</head>



<body style="background-color: rgb(229,243,247);">



<?php
// Set the variables for the database access:
require_once('includes/bootstrap.php');

/* This page receives and handles the data generated by "insertInventoryForm.html". */
// Trim the incoming data.

$title = trim($_POST['Title']);
$productionCompany = trim($_POST['ProductionCompany']);
$yearReleased = trim($_POST['YearReleased']);

if(isset($_POST['submitMovie'])) {
    $director = trim($_POST['Director']);
    $newMovie = new Movie(0, $title, $productionCompany, $yearReleased, $director);
    $result = $newMovie->create($dbc);
} else {
    $album = trim($_POST['Album']);
    $newMusic = new Music(0, $title, $productionCompany, $yearReleased, $album);
    $result = $newMusic->create($dbc);
}

if($result) {
	print "The query was successfully executed!<br />";
} else {
	print "The query could not be executed!<br />";
}

?>
</body>
</html>
